budget_book/urls.py
from django import urls
from django.urls import path
from budget_book import views

app_name = 'dashboard'
urlpatterns=[

    path('', views.index, name='index'),
    path('commimtment/', views.displaycommitment, name='savecommitment'),
    path('opening-balance/', views.displayopeningbalance, name='addopeningbalance'),
    path('receivable-amount', views.displayreceivableamount, name='addreceivableamount'),
    path('year', views.displayyear, name='addyear'),
    path('save-commitment/', views.savecommitment, name='save_commit'),
    path('save-year/', views.addyear, name='save_year'),
    path('save-receivableamount/', views.addreceivableamount, name='save_receive'),
    path('save-openingbalance/', views.addopeningbalance, name='save_openbalance'),
]

cash_report/urls.py
from django.urls import path
from cash_report import views

app_name = 'cashreport'
urlpatterns=[

    path('DailyReport/', views.DailyReport, name='DailyReport'),
    path('export-csv', views.export_csv, name='export-csv'),
    path('export-pdf/', views.export_pdf, name='export-pdf'),
    path('export-excel/', views.export_excel, name='export-excel'),
    # path('commimtment/', views.savecommitment, name='savecommitment'),
    # path('opening-balance/', views.addopeningbalance, name='addopeningbalance'),
    # path('receivable-amount', views.addreceivableamount, name='addreceivableamount'),
    # path('year', views.addyear, name='addyear'),
]

cashmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget_book.urls')),
    path('cashreport/', include('cash_report.urls')),
]

templates/partials/_footer.html
  <!-- Footer -->
  <footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
   <span class="year"></span> Cashmanagement
    </footer>

templates/partials/_mainnavigation.html
<!-- Main Sidebar Container -->
<!--<aside class="main-sidebar sidebar-dark-primary elevation-4">-->
<!-- Brand Logo -->
<!--<a href="index3.html" class="brand-link">
        <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>
</aside>-->

<!-- @using static ExportToExcel.Helpers.NavigationIndicatorHelper; -->


<aside class="main-sidebar sidebar-dark-primary elevation-4" style="overflow-x: hidden; height: 100%">
    <a href="~/Home" class="brand-link">
        <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">CashManagement</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/img/user2.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Reports</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item ">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Home
                        </p>
                    </a>
                </li>
                <li class="nav-item ">
                    <a asp-controller="Home" asp-action="Privacy" class="nav-link">
                        <i class="nav-icon fas fa-lock"></i>
                        <p>
                            Privacy
                        </p>
                    </a>
                </li>
                <li class="nav-item ">
                    <a asp-controller="Add" asp-action="AddBalances" class="nav-link" href="{% url 'dashboard:addopeningbalance' %}">
                        <i class="nav-icon fas fa-money-check-alt"></i>
                        <p>
                            Opening Balance
                        </p>
                    </a>
                </li>
                <li class="nav-item ">
                    <a asp-controller="Add" asp-action="AddCommitments" class="nav-link" href="{% url 'dashboard:savecommitment' %}">
                        <i class="nav-icon fas fa-handshake"></i>
                        <p>
                            Commitment
                        </p>
                    </a>
                </li>
                <li class="nav-item ">
                    <a asp-controller="Add" asp-action="Create" class="nav-link" href="{% url 'dashboard:addreceivableamount' %}">
                        <i class="nav-icon fas fa-money-bill-wave"></i>
                        <p>
                            Receivable Amount
                        </p>
                    </a>
                </li>
                <li class="nav-item ">
                    <a asp-controller="Add" asp-action="AddYear" class="nav-link" href="{% url 'dashboard:addyear' %}">
                        <i class="nav-icon fas fa-calendar-day"></i>
                        <p>
                            Year
                        </p>
                    </a>
                </li>

                <li class="nav-item ">
                    <a asp-controller="CashReport" asp-action="Index" class="nav-link" href="{% url 'cashreport:DailyReport' %}">
                        <i class="nav-icon fas fa-file-archive"></i>
                        <p>
                            Report
                        </p>
                    </a>
                </li>
                <li class="nav-item ">
                    <a asp-area="Identity" asp-page="/Account/Register" class="nav-link" href="{% url 'cashreport:DailyReport' %}">
                        <i class="nav-icon fas fa-registered"></i>
                        <p>
                            Creating Account
                        </p>

                       
                    </a>
                    <!-- <a asp-controller="Home" asp-action="Register" class="nav-link">
                            <i class="nav-icon fas fa-registered"></i>
                            <p>
                                Creating Account
                            </p>
                        </a> -->
                </li>
            </ul>
        </nav>
    </div>
</aside>

templates/partials/_topnavbar.html
  <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

templates/partials/base.html
{% load static %}
{% include 'partials/_topnavbar.html' %}
{% include 'partials/_mainnavigation.html' %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} {% endblock %}</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  </head>
  <body>
   
    
    <!-- Optional JavaScript; choose one of the two! -->
    {% block content %}
    
    {% endblock content %}
    {% include 'partials/_footer.html' %}
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <!-- REQUIRED SCRIPTS -->
 
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
  </body>
</html>


  
  <script>$(function() {
    $( "#datepicker" ).datepicker({dateFormat: 'yy'});
  });​</script>
</html>