budget_book/urls.py
from django import urls
from django.urls import path
from budget_book import views

app_name = 'dashboard'
urlpatterns=[

    path('', views.index, name='index'),
    path('commimtment/', views.displaycommitment, name='savecommitment'),
    path('opening-balance/', views.displayopeningbalance, name='addopeningbalance'),
    path('receivable-amount', views.displayreceivableamount, name='addreceivableamount'),
    path('year', views.displayyear, name='addyear'),
    path('save-commitment/', views.savecommitment, name='save_commit'),
    path('save-year/', views.addyear, name='save_year'),
    path('save-receivableamount/', views.addreceivableamount, name='save_receive'),
    path('save-openingbalance/', views.addopeningbalance, name='save_openbalance'),
]

cashmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget_book.urls')),
    path('cashreport/', include('cash_report.urls')),
]

budget_book/models.py
from django.db import models

# Create your models here.
class Year(models.Model):
    fiscal_year = models.IntegerField() 
    def __str__(self):
     return str(self.fiscal_year)
   

class Commitment(models.Model):
    amount = models.DecimalField(db_column='Amount', max_digits=18, decimal_places=2)  
    donorname = models.TextField(db_column='DonorName', blank=True, null=True)  
    year = models.ForeignKey(Year, on_delete=models.DO_NOTHING, related_name="commitment")

    def __str__(self):
     return str(self.amount)


   


class Openingbalance(models.Model):
    opening_amount = models.DecimalField(max_digits=18, decimal_places=2)  
    account_name = models.CharField(max_length=200)  
    year = models.ForeignKey(Year, on_delete=models.DO_NOTHING, related_name="openingbalance")

    def __str__(self):
        return str(self.opening_amount)



class Receivable(models.Model):
    recieveable_amount = models.DecimalField(max_digits=18, decimal_places=2) 
    name = models.TextField(blank=True, null=True)  
    year = models.ForeignKey(Year, on_delete=models.DO_NOTHING, related_name="receivable")

    def __str__(self):
        return str(self.recieveable_amount),self.name

budget_book/views.py
from os import name
from django.shortcuts import render
from django.http import HttpResponse
from .models import Year, Commitment, Openingbalance, Receivable

# Create your views here.
def index(request):
    
    # return HttpResponse('Cashmanagement')
    return render(request, 'budget_book/index.html')

def displaycommitment(request):
    # return HttpResponse('Cashmanagement')
    queryset = Year.objects.all()
    context={
        'years': queryset
    }
    return render(request, 'budget_book/commitment.html', context)
# def savecommitment(request):
#     # return HttpResponse('Cashmanagement')
#     queryset = Year.objects.all()
#     context={
#         'years': queryset
#     }
#     return render(request, 'budget_book/commitment.html', context)


def savecommitment(request):
    if request.method == 'POST':
        amount = request.POST['amount']
        donorname = request.POST['donername']
        year_id = request.POST['year']

        year = Year.objects.get(id=year_id)

        commitment = Commitment.objects.create(amount=amount, donorname=donorname, year=year)
        commitment.save()
    
    
    return render(request, 'budget_book/commitment.html')


def displayopeningbalance(request):
    return render(request, 'budget_book/openingbalance.html')

def displayreceivableamount(request):
    return render(request, 'budget_book/receiveble.html')

def displayyear(requst):
    return render(requst, 'budget_book/year.html')

def addopeningbalance(request):
    if request.method == 'POST':
        opening_amount = request.POST['openingamount']
        account_name = request.POST['accountname']
        year_id =request.POST['year']
        year = Year.objects.get(id=year_id)
        openingbalance = Openingbalance.objects.create(opening_amount=opening_amount, account_name=account_name, year=year)
        openingbalance.save()
         
    return render(request, 'budget_book/openingbalance.html')

def addreceivableamount(request):
    if request.methode =='POST':
       recieveable_amount = request.POST['recieveable_amount']
       name = request.POST['name']
       year_id = request.POST['year']
       year = Year.objects.get(id=year_id)     
       receivableamount = Receivable.objects.create(recieveable_amount=recieveable_amount, name=name, year=year)
       receivableamount.save()
    return render(request, 'budget_book/receiveble.html')

def addyear(requst):
    if requst.method == 'POST':
        year = requst.POST['year']
        yearadd= Year.objects.create(year=year)
        yearadd.save() 
    return render(requst, 'budget_book/year.html')

templates/budget_book/commitment.html
{% extends 'partials/base.html' %}
{% block title %}Commitment Page{% endblock %}

{% block content %}
   <br>
    <!-- <section id="commimtment" class="bg-light py-5"> -->
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-lg-9">
              <div class="card card-primary card-outline">
                <!-- <div class="card-header bg-primary text-white">
                  <h4>
                    <i class="fas fa-user-plus"></i> Register</h4>
                </div> -->
                <div class="card-body">
                    
                    <form action="{% url 'dashboard:save_commit' %}" method="POST">
                        {% csrf_token %}
                    <!-- <div class="form-group" style="display: flex;">
                      <label class="col-sm-2 text-left" for="first_name">Amount</label>
                      <input type="text" name="first_name" class="col-sm-10 field-amount" required>
                    </div> -->
                    <div class="form-group">
                      <label for="last_name">Amount</label>
                      <input type="text" name="amount" class="form-control" required>
                    </div>
                    <div class="form-group">
                      <label for="username">Donor Name</label>
                      <input type="text" name="donername" class="form-control" required>
                    </div>
                    <div class="dropdown">
                        <label for="year">Year</label>
                        <select class="form-control" name="year">
                            <option selected="selected" disabled>Select year</option>
                            {% for year in years %}
                                    <option value="{{year.id}}">{{year.fiscal_year}}</option>
                            {% endfor %}
                            </select>
                        </div>
                      </div>
                    <input type="submit" value="Save" class="btn btn-secondary btn-block">
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <hr>
        <!-- <div class="contianer">
        <form>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div> -->

        <!-- <div class="container">
            <!-- Horizonatal Form -->
            <div class="row">
              <div class="col-xs-6">
                <form class="form-horizontal">
                  <div class="form-group">
                    <label for="nameField" class="col-xs-2">Name</label>
                    <div class="col-xs-10">
                      <input type="text" class="form-control" id="nameField" placeholder="Your Name" />
                    </div>
                  </div>
                
                  <div class="form-group">
                    <label for="emailField" class="col-xs-2">Email</label>
                    <div class="col-xs-10">
                      <input type="email" class="form-control" id="emailField" placeholder="Your Email" />
                    </div>
                  </div>
                
                  <div class="form-group">
                    <label for="phoneField" class="col-xs-2">Phone</label>
                    <div class="col-xs-10">
                      <input type="text" class="form-control" id="phoneField" placeholder="Your Phone Number" />
                    </div>
                  </div>
                
                  <div class="form-group">
                    <label for="descField" class="col-xs-2">Description</label>
                    <div class="col-xs-10">
                      <textarea type="text" class="form-control" id="descField" placeholder="Your Comments"></textarea>
                    </div>
                  </div>
                  
                  <div class="col-xs-10 col-xs-offset-2">
                    <button type="submit" class="btn btn-primary">Submit</button> <button type="reset" class="btn btn-default">Reset</button>
                  </div>
                  
                </form>
              </div>
            </div>
          </div> -->
      <!-- </section> -->
{% endblock %}

templates/budget_book/index.html
{% extends 'partials/base.html' %}

{% block content%}
{% include 'partials/_topnavbar.html' %}
{% include 'partials/_mainnavigation.html' %}
{% include 'partials/_footer.html' %}
{% endblock content%}

templates/budget_book/openingbalance.html
{% extends 'partials/base.html' %}
{% block title %}Opening Balance Page{% endblock %}


{% block content %}
<br>
<div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-9">
        <div class="card card-primary card-outline">
          
          <div class="card-body">
              
              <form action="{% url 'dashboar:save_openbalance' %}" method="POST">
                  {% csrf_token %}
              <!-- <div class="form-group" style="display: flex;">
                <label class="col-sm-2 text-left" for="first_name">Amount</label>
                <input type="text" name="first_name" class="col-sm-10 field-amount" required>
              </div> -->
              <div class="form-group">
                <label for="last_name">Amount</label>
                <input type="text" name="openingamount" class="form-control" required>
              </div>
              <div class="form-group">
                <label for="username">Donor Name</label>
                <input type="text" name="accountname" class="form-control" required>
              </div>
              <div class="dropdown">
                  <label for="year">Year</label>
                  <select class="form-control" name="year">
                      <option selected="selected" disabled>Select year</option>
                      {% for year in years %}
                              <option value="{{year.id}}">{{year.fiscal_year}}</option>
                      {% endfor %}
                      </select>
                  </div>
                </div>
              <input type="submit" value="Save" class="btn btn-secondary btn-block">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/budget_book/receiveble.html
{% extends 'partials/base.html' %}
{% block title %}Receiveable Amount Page{% endblock %}




{% block content %}
<br>
<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-9">
      <div class="card card-primary card-outline">
        <!-- <div class="card-header bg-primary text-white">
          <h4>
            <i class="fas fa-user-plus"></i> Register</h4>
        </div> -->
        <div class="card-body">
            
            <form action="{% url 'dashboar:save_receive' %}" method="POST">
                {% csrf_token %}
            <!-- <div class="form-group" style="display: flex;">
              <label class="col-sm-2 text-left" for="first_name">Amount</label>
              <input type="text" name="first_name" class="col-sm-10 field-amount" required>
            </div> -->
            <div class="form-group">
              <label for="last_name">Amount</label>
              <input type="text" name="recieveable_amount" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="username">Donor Name</label>
              <input type="text" name="name" class="form-control" required>
            </div>
            <div class="dropdown">
                <label for="year">Year</label>
                <select class="form-control" name="year">
                    <option selected="selected" disabled>Select year</option>
                    {% for year in years %}
                            <option value="{{year.id}}">{{year.fiscal_year}}</option>
                    {% endfor %}
                    </select>
                </div>
              </div>
            <input type="submit" value="Save" class="btn btn-secondary btn-block">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/budget_book/year.html
{% extends 'partials/base.html' %}
{% block title %}Add Year Page{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-9">
        <div class="card card-primary card-outline">
          <!-- <div class="card-header bg-primary text-white">
            <h4>
              <i class="fas fa-user-plus"></i> Register</h4>
          </div> -->
          <div class="card-body">
              
              <form action="{% url 'dashboar:save_year' %}" method="POST">
                  {% csrf_token %}
              <!-- <div class="form-group" style="display: flex;">
                <label class="col-sm-2 text-left" for="first_name">Amount</label>
                <input type="text" name="first_name" class="col-sm-10 field-amount" required>
              </div> -->
              <div class="form-group">
                <label for="last_name">Amount</label>
                <input type="text" name="last_name" class="form-control" required>
              </div>
              <div class="form-group">
                <label for="username">Donor Name</label>
                <input type="text" name="username" class="form-control" required>
              </div>
              <div class="dropdown">
                  <label for="year">Year</label>
                  <select class="form-control" name="dropdown">
                      <option selected="selected" disabled>Select year</option>
                      {% for year in years %}
                              <option value="{{year.id}}">{{year.fiscal_year}}</option>
                      {% endfor %}
                      </select>
                  </div>
                </div>
              <input type="submit" value="Save" class="btn btn-secondary btn-block">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}